### ISSUE TITLE
Installation missing libray libgnome-menu-3.0

### ISSUE THREAD

**Issue by rainer2208** [echo-devim/slingswarm#7]
Hi, when I try to install the launcher typing 

     cmake ..

I get the error message : No package 'libgnome-menu-3.0' found

I tried to install the package via "sudo apt install libgnome-menu-3.0", I get the message : libgnome-menu-3-0 is already the newest version (3.13.3-11ubuntu2).

I am working on Ubuntu 18.10, Budgie desktop.

Is there any solution to it? 

Rainer

**Comment by fossfreedom** [comment]
Libraries to compile against  in Debian and Ubuntu usually are suffixed "-dev" - so the gnome-menu library to install is libgnome-menu-3-dev

**Comment by rainer2208** [comment]
You're the man .....
